RDKCOM-3650: RDKBDEV-1611 fix compilation error while loop initial declarations
Reason for change:
| t2parser.c: In function 'processMsgPackConfiguration':
| t2parser.c:1426:9: error: 'for' loop initial declarations are only allowed in C99 mode
|          for (int i=0; i < ReportingAdjustments_array_size; i++){
|          ^
Test Procedure: Sanity.
Risks: None.
Signed-off-by: BijeeshaVS <bvattakaithayilsudha.contractor@libertyglobal.com>

Signed-off-by: Shibu Kakkoth Vayalambron <Shibu_KV@cable.comcast.com>

RDKCOM-3651: RDKBDEV-1610: drop redundant includes of rbus headers

Reason for change:
rbus.h includes the lower level headers such as rbus_object.h, etc so
they do not need to be included again.
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Change-Id: I26336b55cf876cc28f1dcc10d50215c39e8790b5
Signed-off-by: Shibu Kakkoth Vayalambron <Shibu_KV@cable.comcast.com>

RDKCOM-3652: RDKBDEV-1609: avoid repeated mutex lock/unlock

Reason for change:
avoid repeated mutex lock/unlock in ProfileXConf_storeMarkerEvent()
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Change-Id: I8b3d2969062dccc9c4ffc08b086c9d38901522ef
Signed-off-by: Shibu Kakkoth Vayalambron <Shibu_KV@cable.comcast.com>

RDKCOM-3653: RDKBDEV-1608: autotools cleanup + drop legacy AM_CFLAGS

Reason for change:
Autotools cleanup
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Change-Id: Iff972846a580b8f5a6b6a566ce20c78d0219400d
Signed-off-by: Shibu Kakkoth Vayalambron <Shibu_KV@cable.comcast.com>
(cherry picked from commit 7464b411996513d7082d5b40232c3b5c8c9fdba8)